apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcpgateway
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: mcpgateway-service
                port:
                  number: 8000
