apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: khimnguynnn
  annotations:
    google.com/email: khimnguynn@gmail.com
spec:
  profile:
    displayName: Khiem Nguyen
    email: khimnguynn@gmail.com
  memberOf: []
