---
# Source: chartmuseum/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teleport
  labels:
    helm.sh/chart: chartmuseum-0.1.0
    app.kubernetes.io/name: teleport
    app.kubernetes.io/instance: teleport
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: chartmuseum/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: teleport
  labels:
    helm.sh/chart: chartmuseum-0.1.0
    app.kubernetes.io/name: teleport
    app.kubernetes.io/instance: teleport
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: teleport
    app.kubernetes.io/instance: teleport
---
# Source: chartmuseum/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teleport
  labels:
    helm.sh/chart: chartmuseum-0.1.0
    app.kubernetes.io/name: teleport
    app.kubernetes.io/instance: teleport
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: teleport
      app.kubernetes.io/instance: teleport
  template:
    metadata:
      labels:
        helm.sh/chart: chartmuseum-0.1.0
        app.kubernetes.io/name: teleport
        app.kubernetes.io/instance: teleport
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: teleport
      containers:
        - name: chartmuseum
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
# Source: chartmuseum/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "teleport-test-connection"
  labels:
    helm.sh/chart: chartmuseum-0.1.0
    app.kubernetes.io/name: teleport
    app.kubernetes.io/instance: teleport
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['teleport:80']
  restartPolicy: Never
