apiVersion: v2
name: homepage
description: Homepage - a modern, highly customizable application dashboard
type: application
version: 2.1.0
dependencies:
  - name: homepage
    version: "2.1.0"
    repository: https://jameswynn.github.io/helm-charts
