app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.8.8
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: cloudflare-tunnel
      hosts:
        - host: homepage.0xk3m.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
  persistence:
    config:
      enabled: true
      type: configMap
      name: gethomepage-config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
  configMaps:
    config:
      enabled: true
      data:
        settings.yaml: |
          background: https://images.unsplash.com/photo-1635322966219-b75ed372eb01?auto=format&fit=crop&w=2560&q=80
          cardBlur: md
          theme: dark
          headerStyle: boxed
          hideVersion: true
        widgets.yaml: |
          - search:
              provider: google
              target: _blank
        services.yaml: |
            - ArgoCD:
                href: https://argocd.0xk3m.dev
                description: Continuous deployment
                icon: argocd.svg
            - Grafana:
                href: https://grafana.0xk3m.dev
                description: Observability dashboards
                icon: grafana.svg
        bookmarks.yaml: |
          - Homelab:
            - Public homelab repository:
              - href: https://github.com/khimnguynnn/0xk3m-homelabs
                icon: github.svg
          - Managed services:
            - Cloudflare:
              - href: https://dash.cloudflare.com
                icon: cloudflare.svg
            - Terraform Cloud:
              - href: https://app.terraform.io
                icon: terraform.svg
          - Infrastructure:
            - Proxmox:
              - href: https://192.168.73.10
                icon: router.svg
            - Google Cloud:
              - href: https://console.cloud.google.com
                icon: google-cloud-platform.svg
            - AWS Cloud:
              - href: https://khiemnd.awsapps.com/start
                icon: amazon-web-services.svg
