apiVersion: v2
name: loki
description: Loki - log aggregation system
type: application
version: 6.30.1
dependencies:
  - name: loki
    version: "6.30.1"
    repository: https://grafana.github.io/helm-charts
  - name: external-secret-helper
    version: 0.1.0
    repository: https://charts.0xk3m.dev
