apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcpgateway-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-sa
  namespace: {{ .Release.Namespace }}
