apiVersion: v1
kind: Service
metadata:
  name: mcpgateway-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: mcpgateway
  ports:
    - name: http
      port: 8000
      targetPort: 8000
