# strrl chart: values nest under the dependency name
cloudflare-tunnel-ingress-controller:
  cloudflare:
    secretRef:
      name: cloudflare-tunnel-secrets
      accountIDKey: accountId
      tunnelNameKey: tunnelName
      apiTokenKey: apiToken

external-secret-helper:
  externalSecrets:
    - name: cloudflare-tunnel-secrets
      refreshInterval: 1h
      data:
        - secretKey: accountId
          remoteRef:
            key: gateway/cloudflare-tunnel-ingress-controller
            property: accountId
        - secretKey: apiToken
          remoteRef:
            key: gateway/cloudflare-tunnel-ingress-controller
            property: apiToken
        - secretKey: tunnelName
          remoteRef:
            key: gateway/cloudflare-tunnel-ingress-controller
            property: tunnelName
