external-secrets:
  installCRDs: true

  replicaCount: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  serviceAccount:
    create: true
    name: external-secrets

  webhook:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

  certController:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

external-secret-store:
  stores:
    - name: vault-backend
      kind: ClusterSecretStore
      provider:
        vault:
          server: http://vault.platform.svc:8200
          path: secret
          version: v2
          auth:
            kubernetes:
              mountPath: kubernetes
              role: eso
