{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-secrets
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ include "app.fullname" . }}-secrets
  {{- with .Values.externalSecret.secrets }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.externalSecret.secretFiles }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-secretfiles
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ include "app.fullname" . }}-secretfiles
  data:
    {{- toYaml .Values.externalSecret.secretFiles | nindent 4 }}
{{- end }}
{{- end }}
