{{- range .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: {{ .refreshInterval | default $.Values.defaults.refreshInterval }}
  secretStoreRef:
    name: {{ dig "secretStore" "name" $.Values.defaults.secretStore.name . }}
    kind: {{ dig "secretStore" "kind" $.Values.defaults.secretStore.kind . }}
  target:
    name: {{ .name }}
  {{- with .data }}
  data:
    {{- range . }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        conversionStrategy: {{ .remoteRef.conversionStrategy | default "Default" }}
        decodingStrategy: {{ .remoteRef.decodingStrategy | default "None" }}
        key: {{ .remoteRef.key }}
        metadataPolicy: {{ .remoteRef.metadataPolicy | default "None" }}
        {{- with .remoteRef.property }}
        property: {{ . }}
        {{- end }}
    {{- end }}
  {{- end }}
---
{{- end }}
