{{- range .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: {{ .refreshInterval | default $.Values.defaults.refreshInterval }}
  secretStoreRef:
    name: {{ dig "secretStore" "name" $.Values.defaults.secretStore.name . }}
    kind: {{ dig "secretStore" "kind" $.Values.defaults.secretStore.kind . }}
  target:
    name: {{ .name }}
  {{- with .data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
