apiVersion: v2
name: backstage
description: Backstage - Internal Developer Portal
type: application
version: 2.10.0
dependencies:
  - name: backstage
    version: "2.10.0"
    repository: https://backstage.github.io/charts
  - name: external-secret-helper
    version: 0.1.0
    repository: https://charts.0xk3m.dev
