backstage:
  backstage:
    replicas: 1

    image:
      # registry: docker.io
      # repository: khimnguynn/backstage
      # tag: latest
      registry: ghcr.io
      repository: backstage/backstage
      tag: latest
      pullPolicy: IfNotPresent

    containerSecurityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

    extraEnvVarsSecrets:
      - backstage-secrets

    extraEnvVars:
      - name: APP_CONFIG_app_baseUrl
        value: "https://backstage.0xk3m.dev"
      - name: APP_CONFIG_backend_baseUrl
        value: "https://backstage.0xk3m.dev"

    appConfig:
      app:
        title: 0xk3m Homelab
        baseUrl: https://backstage.0xk3m.dev
      auth:
        environment: homelab
        providers:
          google:
            homelab:
              clientId: ${GOOGLE_CLIENT_ID}
              clientSecret: ${GOOGLE_CLIENT_SECRET}
              callbackUrl: https://backstage.0xk3m.dev/api/auth/google/callback
              signIn:
                resolvers:
                  - resolver: emailMatchingUserEntityAnnotation
      backend:
        baseUrl: https://backstage.0xk3m.dev
        listen:
          port: 7007
        csp:
          connect-src: ["'self'", "http:", "https:"]
        cors:
          origin: https://backstage.0xk3m.dev
          methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
          credentials: true

      catalog:
        rules:
          - allow:
              [Component, System, API, Resource, Location, Domain, Group, User]
        locations: []

  ingress:
    enabled: true
    className: cloudflare-tunnel
    annotations:
      cloudflare-tunnel-ingress-controller.cfargotunnel.com/enabled: "true"
    host: backstage.0xk3m.dev
    path: /
    tls:
      enabled: false

  service:
    type: ClusterIP
    ports:
      backend: 7007

  postgresql:
    enabled: true
    auth:
      username: backstage
      database: backstage
      existingSecret: backstage-secrets
      secretKeys:
        adminPasswordKey: admin-password
        userPasswordKey: user-password

external-secret-helper:
  externalSecrets:
    - name: backstage-secrets
      refreshInterval: 1h
      data:
        - secretKey: admin-password
          remoteRef:
            key: platform/backstage
            property: postgresPassword
        - secretKey: user-password
          remoteRef:
            key: platform/backstage
            property: postgresPassword
        - secretKey: GOOGLE_CLIENT_ID
          remoteRef:
            key: platform/backstage
            property: GOOGLE_CLIENT_ID
        - secretKey: GOOGLE_CLIENT_SECRET
          remoteRef:
            key: platform/backstage
            property: GOOGLE_CLIENT_SECRET
